/**
 * Predefined mock data served by all admin API routes when Supabase is
 * not configured. Gives a fully functional admin experience out-of-the-box.
 */
import type { Order, FbConversation, FbMessage, MessageSignals } from "./types";

const D = (hoursAgo: number) =>
  new Date(Date.now() - hoursAgo * 3_600_000).toISOString();

function sig(s: Partial<MessageSignals>): string {
  return JSON.stringify({
    urls: [], phones: [], addressHints: [], prices: [], sizes: [],
    isLikelyOrder: false, score: 0, ...s,
  });
}

/** All mock messages keyed by conversation ID */
export const MOCK_MESSAGES: Record<string, FbMessage[]> = {
  mock_conv_nadia_001: [
    {
      id: "msg_nadia_1",
      conversationId: "mock_conv_nadia_001",
      fromType: "customer",
      text: "Assalamu alaikum bhai! ASOS theke ei dress ta ki pathate parben? https://www.asos.com/pimki/pimki-ribbed-knit-midi-dress/prd/204567891 Size 10 lagbe. Uttara 7 no sector e deliver korben. Amar number 01712345678",
      attachmentsJson: null,
      signalsJson: sig({
        urls: ["https://www.asos.com/pimki/pimki-ribbed-knit-midi-dress/prd/204567891"],
        phones: ["01712345678"],
        addressHints: ["Uttara, Dhaka"],
        sizes: ["10"],
        isLikelyOrder: true,
        score: 85,
        extractedCity: "Uttara, Dhaka",
      }),
      channel: "facebook",
      createdAt: D(8),
    },
    {
      id: "msg_nadia_2",
      conversationId: "mock_conv_nadia_001",
      fromType: "page",
      text: "Wa alaikum assalam! Ji, ASOS theke pathano jay. £28.99 + shipping. Quote pathabo ajkei.",
      attachmentsJson: null,
      signalsJson: null,
      channel: "facebook",
      createdAt: D(7.5),
    },
    {
      id: "msg_nadia_3",
      conversationId: "mock_conv_nadia_001",
      fromType: "customer",
      text: "Okay! BDT te koto hobe? Address: House 12, Road 7, Sector 7, Uttara, Dhaka 1230",
      attachmentsJson: null,
      signalsJson: sig({
        addressHints: ["House 12, Road 7, Sector 7, Uttara, Dhaka 1230"],
        isLikelyOrder: true,
        score: 75,
        extractedCity: "Uttara, Dhaka",
      }),
      channel: "facebook",
      createdAt: D(7),
    },
  ],

  mock_conv_rafiq_002: [
    {
      id: "msg_rafiq_1",
      conversationId: "mock_conv_rafiq_002",
      fromType: "customer",
      text: "Bhai Amazon UK theke ei Nike Air Max ta pathaben? https://www.amazon.co.uk/Nike-Air-Max-270/dp/B08XYZ12345 - size 9 UK lagbe. Phone: 01891234567",
      attachmentsJson: null,
      signalsJson: sig({
        urls: ["https://www.amazon.co.uk/Nike-Air-Max-270/dp/B08XYZ12345"],
        phones: ["01891234567"],
        sizes: ["9 UK"],
        prices: ["£89.99"],
        isLikelyOrder: true,
        score: 80,
      }),
      channel: "facebook",
      createdAt: D(26),
    },
    {
      id: "msg_rafiq_2",
      conversationId: "mock_conv_rafiq_002",
      fromType: "customer",
      text: "Chittagong Agrabad te deliver korben. Koto din lagbe?",
      attachmentsJson: null,
      signalsJson: sig({
        addressHints: ["Chittagong Agrabad"],
        isLikelyOrder: true,
        score: 60,
        extractedCity: "Chittagong",
      }),
      channel: "facebook",
      createdAt: D(25.5),
    },
    {
      id: "msg_rafiq_3",
      conversationId: "mock_conv_rafiq_002",
      fromType: "page",
      text: "Ji bhai! Amazon UK theke Nike Air Max pathano jabe inshaAllah. UK size 9 available ache. Chittagong deliver hobe 10-14 din er modhye. Full quote SMS korchi ajkei 🙏",
      attachmentsJson: null,
      signalsJson: null,
      channel: "facebook",
      createdAt: D(24),
    },
  ],

  mock_conv_tasmin_003: [
    {
      id: "msg_tasmin_1",
      conversationId: "mock_conv_tasmin_003",
      fromType: "customer",
      text: "Hello! Harrods theke La Mer cream ta ki available? https://www.harrods.com/en-gb/beauty/la-mer - 60ml size. Price koto hobe total?",
      attachmentsJson: null,
      signalsJson: sig({
        urls: ["https://www.harrods.com/en-gb/beauty/la-mer"],
        sizes: ["60ml"],
        prices: ["£145"],
        isLikelyOrder: true,
        score: 70,
      }),
      channel: "facebook",
      createdAt: D(20),
    },
  ],

  mock_conv_karim_004: [
    {
      id: "msg_karim_1",
      conversationId: "mock_conv_karim_004",
      fromType: "customer",
      text: "Bhai amar order er ki update ache? Order number AN-20260523-DD44. Onek din hoyeche.",
      attachmentsJson: null,
      signalsJson: sig({ score: 20 }),
      channel: "facebook",
      createdAt: D(60),
    },
    {
      id: "msg_karim_2",
      conversationId: "mock_conv_karim_004",
      fromType: "page",
      text: "Apnar order UK theke ship hoyeche, BD customs e ache. 3-5 din er modhye pouchabe inshaAllah.",
      attachmentsJson: null,
      signalsJson: null,
      channel: "facebook",
      createdAt: D(58),
    },
    {
      id: "msg_karim_3",
      conversationId: "mock_conv_karim_004",
      fromType: "customer",
      text: "Okay thank you! Customs e kono problem hobe na to?",
      attachmentsJson: null,
      signalsJson: sig({ score: 15 }),
      channel: "facebook",
      createdAt: D(40),
    },
  ],

  mock_conv_farhana_007: [
    {
      id: "msg_farhana_1",
      conversationId: "mock_conv_farhana_007",
      fromType: "customer",
      text: "Selfridges theke Gucci GG Marmont mini bag order korte chai. Black color lagbe. https://www.selfridges.com/GB/en/cat/gucci-gg-marmont-mini",
      attachmentsJson: null,
      signalsJson: sig({
        urls: ["https://www.selfridges.com/GB/en/cat/gucci-gg-marmont-mini"],
        prices: ["£1,150"],
        isLikelyOrder: true,
        score: 75,
      }),
      channel: "facebook",
      createdAt: D(380),
    },
    {
      id: "msg_farhana_2",
      conversationId: "mock_conv_farhana_007",
      fromType: "page",
      text: "Ji apu, Gucci GG Marmont pathano jabe. Black available ache Selfridges e. £1,150 + shipping + customs — approximate ৳1,75,000 hobe. Confirm korben?",
      attachmentsJson: null,
      signalsJson: null,
      channel: "facebook",
      createdAt: D(370),
    },
    {
      id: "msg_farhana_3",
      conversationId: "mock_conv_farhana_007",
      fromType: "customer",
      text: "Okay, order cancel kore din. Budget nei.",
      attachmentsJson: null,
      signalsJson: sig({ score: 10 }),
      channel: "facebook",
      createdAt: D(300),
    },
  ],
};

export const MOCK_ORDERS: Order[] = [
  {
    id: "mock-ord-001",
    orderNumber: "AN-20260527-AA11",
    customerName: "Nadia Akter",
    phone: "01712345678",
    email: "nadia@example.com",
    address: "House 12, Road 7, Sector 7",
    city: "Uttara, Dhaka",
    paymentMethod: "bKash",
    source: "facebook",
    status: "pending",
    quoteAmount: null,
    quoteCurrency: "BDT",
    fbConversationId: "mock_conv_nadia_001",
    notes: "Please wrap carefully",
    items: [
      {
        productUrl: "https://www.asos.com/pimki/pimki-ribbed-knit-midi-dress/prd/204567891",
        siteName: "ASOS",
        productName: "Pimki Ribbed Knit Midi Dress",
        variantNotes: "Size 10, Black",
        price: "£28.99",
        currency: "GBP",
        quantity: 1,
      },
    ],
    createdAt: D(8),
    updatedAt: D(8),
  },
  {
    id: "mock-ord-002",
    orderNumber: "AN-20260526-BB22",
    customerName: "Rafiqul Hasan",
    phone: "01891234567",
    email: "rafiq@example.com",
    address: "House 5, Agrabad Commercial Area",
    city: "Chittagong",
    paymentMethod: "Nagad",
    source: "facebook",
    status: "quoted",
    quoteAmount: 13500,
    quoteCurrency: "BDT",
    fbConversationId: "mock_conv_rafiq_002",
    notes: "",
    items: [
      {
        productUrl: "https://www.amazon.co.uk/Nike-Air-Max-270/dp/B08XYZ12345",
        siteName: "Amazon UK",
        productName: "Nike Air Max 270",
        variantNotes: "UK Size 9, White/Black",
        price: "£89.99",
        currency: "GBP",
        quantity: 1,
      },
    ],
    createdAt: D(26),
    updatedAt: D(20),
  },
  {
    id: "mock-ord-003",
    orderNumber: "AN-20260525-CC33",
    customerName: "Tasmin Begum",
    phone: "01756789012",
    email: "tasmin@example.com",
    address: "Flat 4B, Banani DOHS",
    city: "Dhaka",
    paymentMethod: "Bank Transfer",
    source: "web",
    status: "confirmed",
    quoteAmount: 21500,
    quoteCurrency: "BDT",
    fbConversationId: null,
    notes: "Birthday gift — please add gift wrapping",
    items: [
      {
        productUrl: "https://www.harrods.com/en-gb/beauty/la-mer/the-moisturizing-cream",
        siteName: "Harrods",
        productName: "La Mer The Moisturizing Cream",
        variantNotes: "60ml",
        price: "£145.00",
        currency: "GBP",
        quantity: 1,
      },
    ],
    createdAt: D(52),
    updatedAt: D(30),
  },
  {
    id: "mock-ord-004",
    orderNumber: "AN-20260523-DD44",
    customerName: "Karim Uddin",
    phone: "01611234567",
    email: "",
    address: "House 23, Dhanmondi Road 8",
    city: "Dhaka",
    paymentMethod: "bKash",
    source: "web",
    status: "purchased",
    quoteAmount: 89000,
    quoteCurrency: "BDT",
    fbConversationId: null,
    notes: "",
    items: [
      {
        productUrl: "https://www.johnlewis.com/dyson-v15-detect/p12345",
        siteName: "John Lewis",
        productName: "Dyson V15 Detect Cordless Vacuum",
        variantNotes: "",
        price: "£599.00",
        currency: "GBP",
        quantity: 1,
      },
    ],
    createdAt: D(120),
    updatedAt: D(72),
  },
  {
    id: "mock-ord-005",
    orderNumber: "AN-20260520-EE55",
    customerName: "Sabrina Islam",
    phone: "01987654321",
    email: "sabrina@example.com",
    address: "Holding 33, Gulshan 2",
    city: "Dhaka",
    paymentMethod: "bKash",
    source: "web",
    status: "shipped",
    quoteAmount: 17400,
    quoteCurrency: "BDT",
    fbConversationId: null,
    notes: "Urgent — needed for wedding",
    items: [
      {
        productUrl: "https://www.boots.com/no7-beauty/skincare",
        siteName: "Boots",
        productName: "No7 Future Renew Serum",
        variantNotes: "50ml",
        price: "£34.95",
        currency: "GBP",
        quantity: 2,
      },
      {
        productUrl: "https://www.boots.com/charlotte-tilbury/magic-cream",
        siteName: "Boots",
        productName: "Charlotte Tilbury Magic Cream",
        variantNotes: "50ml",
        price: "£82.00",
        currency: "GBP",
        quantity: 1,
      },
    ],
    createdAt: D(230),
    updatedAt: D(48),
  },
  {
    id: "mock-ord-006",
    orderNumber: "AN-20260515-FF66",
    customerName: "Mahmud Rahman",
    phone: "01312345678",
    email: "mahmud@example.com",
    address: "Village: Osmanpur, Upazila: Sylhet Sadar",
    city: "Sylhet",
    paymentMethod: "bKash",
    source: "manual",
    status: "delivered",
    quoteAmount: 9700,
    quoteCurrency: "BDT",
    fbConversationId: null,
    notes: "Phone order",
    items: [
      {
        productUrl: "https://www.next.co.uk/g/mens-coats",
        siteName: "Next",
        productName: "Shower Resistant Hooded Puffer Jacket",
        variantNotes: "Size L, Navy",
        price: "£65.00",
        currency: "GBP",
        quantity: 1,
      },
    ],
    createdAt: D(340),
    updatedAt: D(96),
  },
  {
    id: "mock-ord-007",
    orderNumber: "AN-20260514-GG77",
    customerName: "Farhana Khanam",
    phone: "01456789012",
    email: "farhana@example.com",
    address: "House 7A, Bashundhara R/A, Block D",
    city: "Dhaka",
    paymentMethod: "Nagad",
    source: "facebook",
    status: "cancelled",
    quoteAmount: null,
    quoteCurrency: "BDT",
    fbConversationId: "mock_conv_farhana_007",
    notes: "",
    items: [
      {
        productUrl: "https://www.selfridges.com/GB/en/cat/gucci-gg-marmont-mini",
        siteName: "Selfridges",
        productName: "Gucci GG Marmont Mini Bag",
        variantNotes: "Black",
        price: "£1,150.00",
        currency: "GBP",
        quantity: 1,
      },
    ],
    createdAt: D(380),
    updatedAt: D(300),
  },
];

export const MOCK_CONVERSATIONS: FbConversation[] = [
  {
    id: "mock_conv_nadia_001",
    customerPsid: "mock_psid_nadia",
    customerName: "Nadia Akter",
    customerAvatar: null,
    lastMessageAt: D(2),
    lastMessageSnippet: "Okay! BDT te koto hobe? Address: House 12, Road 7...",
    unreadCount: 2,
    status: "open",
    isLikelyOrder: true,
    linkedOrderNumber: "AN-20260527-AA11",
    channel: "facebook",
    createdAt: D(8),
    updatedAt: D(2),
  },
  {
    id: "mock_conv_rafiq_002",
    customerPsid: "mock_psid_rafiq",
    customerName: "Rafiqul Hasan",
    customerAvatar: null,
    lastMessageAt: D(6),
    lastMessageSnippet: "Chittagong Agrabad te deliver korben. Koto din lagbe?",
    unreadCount: 1,
    status: "open",
    isLikelyOrder: true,
    linkedOrderNumber: "AN-20260526-BB22",
    channel: "facebook",
    createdAt: D(26),
    updatedAt: D(6),
  },
  {
    id: "mock_conv_tasmin_003",
    customerPsid: "mock_psid_tasmin",
    customerName: "Tasmin Begum",
    customerAvatar: null,
    lastMessageAt: D(18),
    lastMessageSnippet: "Hello! Harrods theke La Mer cream ta ki available?",
    unreadCount: 0,
    status: "open",
    isLikelyOrder: true,
    linkedOrderNumber: null,
    channel: "facebook",
    createdAt: D(20),
    updatedAt: D(18),
  },
  {
    id: "mock_conv_karim_004",
    customerPsid: "mock_psid_karim",
    customerName: "Karim Uddin",
    customerAvatar: null,
    lastMessageAt: D(40),
    lastMessageSnippet: "BD customs e ache. 3-5 din er modhye pouchabe inshaAllah.",
    unreadCount: 0,
    status: "open",
    isLikelyOrder: false,
    linkedOrderNumber: "AN-20260523-DD44",
    channel: "facebook",
    createdAt: D(60),
    updatedAt: D(40),
  },
  {
    id: "mock_conv_farhana_007",
    customerPsid: "mock_psid_farhana",
    customerName: "Farhana Khanam",
    customerAvatar: null,
    lastMessageAt: D(300),
    lastMessageSnippet: "Okay, order cancel kore din. Budget nei.",
    unreadCount: 0,
    status: "archived",
    isLikelyOrder: false,
    linkedOrderNumber: "AN-20260514-GG77",
    channel: "facebook",
    createdAt: D(380),
    updatedAt: D(300),
  },
];

// Re-export the admin key so login page can compare client-side
export const DEMO_ADMIN_KEY = "alynaf-admin";
