/**
 * Predefined mock data served by all admin API routes when Supabase is
 * not configured. Gives a fully functional admin experience out-of-the-box.
 */
import type { Order, FbConversation } from "./types";

const NOW = "2026-05-29T10:00:00.000Z";
const D = (hoursAgo: number) =>
  new Date(Date.now() - hoursAgo * 3_600_000).toISOString();

export const MOCK_ORDERS: Order[] = [
  {
    id: "mock-ord-001",
    orderNumber: "AN-20260527-AA11",
    customerName: "Nadia Akter",
    phone: "01712345678",
    email: "nadia@example.com",
    address: "House 12, Road 7, Sector 7",
    city: "Uttara, Dhaka",
    paymentMethod: "bKash",
    source: "facebook",
    status: "pending",
    quoteAmount: null,
    quoteCurrency: "BDT",
    fbConversationId: "mock_conv_nadia_001",
    notes: "Please wrap carefully",
    items: [
      {
        productUrl: "https://www.asos.com/pimki/pimki-ribbed-knit-midi-dress/prd/204567891",
        siteName: "ASOS",
        productName: "Pimki Ribbed Knit Midi Dress",
        variantNotes: "Size 10, Black",
        price: "£28.99",
        currency: "GBP",
        quantity: 1,
      },
    ],
    createdAt: D(8),
    updatedAt: D(8),
  },
  {
    id: "mock-ord-002",
    orderNumber: "AN-20260526-BB22",
    customerName: "Rafiqul Hasan",
    phone: "01891234567",
    email: "rafiq@example.com",
    address: "House 5, Agrabad Commercial Area",
    city: "Chittagong",
    paymentMethod: "Nagad",
    source: "facebook",
    status: "quoted",
    quoteAmount: 13500,
    quoteCurrency: "BDT",
    fbConversationId: "mock_conv_rafiq_002",
    notes: "",
    items: [
      {
        productUrl: "https://www.amazon.co.uk/Nike-Air-Max-270/dp/B08XYZ12345",
        siteName: "Amazon UK",
        productName: "Nike Air Max 270",
        variantNotes: "UK Size 9, White/Black",
        price: "£89.99",
        currency: "GBP",
        quantity: 1,
      },
    ],
    createdAt: D(26),
    updatedAt: D(20),
  },
  {
    id: "mock-ord-003",
    orderNumber: "AN-20260525-CC33",
    customerName: "Tasmin Begum",
    phone: "01756789012",
    email: "tasmin@example.com",
    address: "Flat 4B, Banani DOHS",
    city: "Dhaka",
    paymentMethod: "Bank Transfer",
    source: "web",
    status: "confirmed",
    quoteAmount: 21500,
    quoteCurrency: "BDT",
    fbConversationId: null,
    notes: "Birthday gift — please add gift wrapping",
    items: [
      {
        productUrl: "https://www.harrods.com/en-gb/beauty/la-mer/the-moisturizing-cream",
        siteName: "Harrods",
        productName: "La Mer The Moisturizing Cream",
        variantNotes: "60ml",
        price: "£145.00",
        currency: "GBP",
        quantity: 1,
      },
    ],
    createdAt: D(52),
    updatedAt: D(30),
  },
  {
    id: "mock-ord-004",
    orderNumber: "AN-20260523-DD44",
    customerName: "Karim Uddin",
    phone: "01611234567",
    email: "",
    address: "House 23, Dhanmondi Road 8",
    city: "Dhaka",
    paymentMethod: "bKash",
    source: "web",
    status: "purchased",
    quoteAmount: 89000,
    quoteCurrency: "BDT",
    fbConversationId: null,
    notes: "",
    items: [
      {
        productUrl: "https://www.johnlewis.com/dyson-v15-detect/p12345",
        siteName: "John Lewis",
        productName: "Dyson V15 Detect Cordless Vacuum",
        variantNotes: "",
        price: "£599.00",
        currency: "GBP",
        quantity: 1,
      },
    ],
    createdAt: D(120),
    updatedAt: D(72),
  },
  {
    id: "mock-ord-005",
    orderNumber: "AN-20260520-EE55",
    customerName: "Sabrina Islam",
    phone: "01987654321",
    email: "sabrina@example.com",
    address: "Holding 33, Gulshan 2",
    city: "Dhaka",
    paymentMethod: "bKash",
    source: "web",
    status: "shipped",
    quoteAmount: 17400,
    quoteCurrency: "BDT",
    fbConversationId: null,
    notes: "Urgent — needed for wedding",
    items: [
      {
        productUrl: "https://www.boots.com/no7-beauty/skincare",
        siteName: "Boots",
        productName: "No7 Future Renew Serum",
        variantNotes: "50ml",
        price: "£34.95",
        currency: "GBP",
        quantity: 2,
      },
      {
        productUrl: "https://www.boots.com/charlotte-tilbury/magic-cream",
        siteName: "Boots",
        productName: "Charlotte Tilbury Magic Cream",
        variantNotes: "50ml",
        price: "£82.00",
        currency: "GBP",
        quantity: 1,
      },
    ],
    createdAt: D(230),
    updatedAt: D(48),
  },
  {
    id: "mock-ord-006",
    orderNumber: "AN-20260515-FF66",
    customerName: "Mahmud Rahman",
    phone: "01312345678",
    email: "mahmud@example.com",
    address: "Village: Osmanpur, Upazila: Sylhet Sadar",
    city: "Sylhet",
    paymentMethod: "bKash",
    source: "manual",
    status: "delivered",
    quoteAmount: 9700,
    quoteCurrency: "BDT",
    fbConversationId: null,
    notes: "Phone order",
    items: [
      {
        productUrl: "https://www.next.co.uk/g/mens-coats",
        siteName: "Next",
        productName: "Shower Resistant Hooded Puffer Jacket",
        variantNotes: "Size L, Navy",
        price: "£65.00",
        currency: "GBP",
        quantity: 1,
      },
    ],
    createdAt: D(340),
    updatedAt: D(96),
  },
  {
    id: "mock-ord-007",
    orderNumber: "AN-20260514-GG77",
    customerName: "Farhana Khanam",
    phone: "01456789012",
    email: "farhana@example.com",
    address: "House 7A, Bashundhara R/A, Block D",
    city: "Dhaka",
    paymentMethod: "Nagad",
    source: "facebook",
    status: "cancelled",
    quoteAmount: null,
    quoteCurrency: "BDT",
    fbConversationId: "mock_conv_farhana_007",
    notes: "",
    items: [
      {
        productUrl: "https://www.selfridges.com/GB/en/cat/gucci-gg-marmont-mini",
        siteName: "Selfridges",
        productName: "Gucci GG Marmont Mini Bag",
        variantNotes: "Black",
        price: "£1,150.00",
        currency: "GBP",
        quantity: 1,
      },
    ],
    createdAt: D(380),
    updatedAt: D(300),
  },
];

export const MOCK_CONVERSATIONS: FbConversation[] = [
  {
    id: "mock_conv_nadia_001",
    customerPsid: "mock_psid_nadia",
    customerName: "Nadia Akter",
    customerAvatar: null,
    lastMessageAt: D(2),
    lastMessageSnippet: "Okay! BDT te koto hobe? Address: House 12, Road 7...",
    unreadCount: 2,
    status: "open",
    isLikelyOrder: true,
    linkedOrderNumber: "AN-20260527-AA11",
    channel: "facebook",
    createdAt: D(8),
    updatedAt: D(2),
  },
  {
    id: "mock_conv_rafiq_002",
    customerPsid: "mock_psid_rafiq",
    customerName: "Rafiqul Hasan",
    customerAvatar: null,
    lastMessageAt: D(6),
    lastMessageSnippet: "Chittagong Agrabad te deliver korben. Koto din lagbe?",
    unreadCount: 1,
    status: "open",
    isLikelyOrder: true,
    linkedOrderNumber: "AN-20260526-BB22",
    channel: "facebook",
    createdAt: D(26),
    updatedAt: D(6),
  },
  {
    id: "mock_conv_tasmin_003",
    customerPsid: "mock_psid_tasmin",
    customerName: "Tasmin Begum",
    customerAvatar: null,
    lastMessageAt: D(18),
    lastMessageSnippet: "Hello! Harrods theke La Mer cream ta ki available?",
    unreadCount: 0,
    status: "open",
    isLikelyOrder: true,
    linkedOrderNumber: null,
    channel: "facebook",
    createdAt: D(20),
    updatedAt: D(18),
  },
  {
    id: "mock_conv_karim_004",
    customerPsid: "mock_psid_karim",
    customerName: "Karim Uddin",
    customerAvatar: null,
    lastMessageAt: D(40),
    lastMessageSnippet: "BD customs e ache. 3-5 din er modhye pouchabe inshaAllah.",
    unreadCount: 0,
    status: "open",
    isLikelyOrder: false,
    linkedOrderNumber: "AN-20260523-DD44",
    channel: "facebook",
    createdAt: D(60),
    updatedAt: D(40),
  },
  {
    id: "mock_conv_farhana_007",
    customerPsid: "mock_psid_farhana",
    customerName: "Farhana Khanam",
    customerAvatar: null,
    lastMessageAt: D(300),
    lastMessageSnippet: "Okay, order cancel kore din. Budget nei.",
    unreadCount: 0,
    status: "archived",
    isLikelyOrder: false,
    linkedOrderNumber: "AN-20260514-GG77",
    channel: "facebook",
    createdAt: D(380),
    updatedAt: D(300),
  },
];

// Re-export the admin key so login page can compare client-side
export const DEMO_ADMIN_KEY = "alynaf-admin";
